fix: download url, install
Signed-off-by: Andrew Duss <andrew.duss@storable.com>

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -18,14 +18,14 @@ install_dapr() {
   local tgz_path="${bin_install_path}/dapr.tgz"
   local bin_path="${bin_install_path}/dapr"
   echo "[*] Downloading dapr-cli from ${download_url}"
-  # if curl -L -sf "$download_url" -o "$bin_path"; then
-  #   tar -xf $tgz_path
-  #   chmod +x $bin_path
-  #   echo "[*] dapr-cli has been installed. Use 'dapr' to get started"
-  # else
-  #   echo "Failed to download dapr-cli from ${download_url}. Does the version exist and is available in the requested $(get_cpu) architecture?"
-  #   exit 1
-  # fi
+  if curl -L -sf "$download_url" -o "$bin_path"; then
+    tar -xf $tgz_path
+    chmod +x $bin_path
+    echo "[*] dapr-cli has been installed. Use 'dapr' to get started"
+  else
+    echo "Failed to download dapr-cli from ${download_url}. Does the version exist and is available in the requested $(get_cpu) architecture?"
+    exit 1
+  fi
 }
 
 get_arch() {
@@ -50,7 +50,7 @@ get_download_url() {
   local version="$1"
   local platform="$(get_arch)"
   # https://github.com/dapr/cli/releases/download/v1.11.0/dapr_darwin_amd64.tar.gz
-  echo "https://github.com/dapr/cli/releases/download/v${version}/dapr_-${platform}_$(get_cpu).tar.gz"
+  echo "https://github.com/dapr/cli/releases/download/v${version}/dapr_${platform}_$(get_cpu).tar.gz"
 }
 
 install_dapr $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
